name: Test

on:
  push: {}
  pull_request: {}

jobs:
  GenerateMatrix:
    runs-on: ubuntu-latest

    outputs:
      node-version: ${{ steps.create-node-matrix.outputs.matrix }}

    steps:
      - name: Create Node Version Matrix
        id: create-node-matrix
        run: |
          NODE_VERSIONS="['20.x']"
          echo "matrix=$NODE_VERSIONS" >> "$GITHUB_OUTPUT"

  Style:
    runs-on: ubuntu-latest

    needs: [GenerateMatrix]
    strategy:
      matrix:
        node-version: ${{ fromJson(needs.GenerateMatrix.outputs.node-version) }}

    permissions:
      checks: write

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm lint:ci --output-file .eslint_report.json --format json
        continue-on-error: true

      - name: Annotate ESLint Results
        uses: ataylorme/eslint-annotate-action@v3
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          report-json: .eslint_report.json
          fail-on-warning: true
          markdown-report-on-step-summary: true

      - name: Run Prettier
        run: pnpm prettier:ci

  Test:
    runs-on: ubuntu-latest

    needs: [GenerateMatrix]
    strategy:
      matrix:
        node-version: ${{ fromJson(needs.GenerateMatrix.outputs.node-version) }}

    permissions:
      checks: write

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Test with vitest
        if: ${{ !cancelled() }}
        run: pnpm run test --reporter=junit

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
